import { ClassDefinition, ClassType, Item, MapDefinition, MapId, Monster, Skill, Player, DEFAULT_BUFFS } from './types';

export const CLASSES: Record<ClassType, ClassDefinition> = {
  warrior: {
    name: 'Templário', emoji: '⚔️',
    description: 'Combatente sagrado com armadura pesada e fé inabalável.',
    baseStats: { hp: 150, mp: 50, attack: 10, defense: 8 },
    special: 'Punição Divina: Ataque duplo que ignora 50% da defesa.',
    unlockedByDefault: true, color: '#e74c3c',
  },
  mage: {
    name: 'Arcanista', emoji: '🔮',
    description: 'Estudioso dos segredos proibidos do cosmos arcano.',
    baseStats: { hp: 80, mp: 150, attack: 14, defense: 2 },
    special: 'Colapso Astral: Dano devastador em área.',
    unlockedByDefault: true, color: '#9b59b6',
  },
  rogue: {
    name: 'Espectro', emoji: '🗡️',
    description: 'Assassino das sombras que opera além da percepção humana.',
    baseStats: { hp: 95, mp: 70, attack: 12, defense: 4 },
    special: 'Decapitação: Dano triplicado, ignora toda defesa.',
    unlockedByDefault: true, color: '#1abc9c',
  },
  necromancer: {
    name: 'Ceifador', emoji: '💀',
    description: 'Sacerdote da morte que comanda legions de almas perdidas.',
    baseStats: { hp: 90, mp: 150, attack: 13, defense: 3 },
    special: 'Legião Sombria: +8 dano ao grupo por 5 turnos.',
    unlockedByDefault: true, color: '#8e44ad',
  },
  paladin: {
    name: 'Cruzado', emoji: '🛡️',
    description: 'Guerreiro da luz que canaliza milagres divinos em batalha.',
    baseStats: { hp: 130, mp: 90, attack: 8, defense: 10 },
    special: 'Milagre Sagrado: Restaura 40HP de todos os aliados.',
    unlockedByDefault: true, color: '#f39c12',
  },
  ranger: {
    name: 'Caçador', emoji: '🏹',
    description: 'Rastreador das terras selvagens, mestre do arco e da emboscada.',
    baseStats: { hp: 100, mp: 90, attack: 12, defense: 5 },
    special: 'Dilúvio de Flechas: Assalta todos os inimigos.',
    unlockedByDefault: true, color: '#3498db',
  },
  assassin: {
    name: 'Ombra', emoji: '🌙',
    description: 'Lâmina viva que existe apenas para extinguir vida.',
    baseStats: { hp: 85, mp: 100, attack: 15, defense: 3 },
    special: 'Guilhotina: 3x dano se o alvo estiver abaixo de 50% HP.',
    unlockedByDefault: true, color: '#2c3e50',
  },
  elementalist: {
    name: 'Cataclista', emoji: '🌊',
    description: 'Canaliza as forças primordiais do universo em destruição pura.',
    baseStats: { hp: 80, mp: 160, attack: 13, defense: 2 },
    special: 'Colapso Tríplice: Ataca todos com fogo, gelo e raio.',
    unlockedByDefault: true, color: '#e67e22',
  },
  berserker: {
    name: 'Flagelante', emoji: '🪓',
    description: 'Guerreiro amaldiçoado cuja raiva cresce com cada ferida.',
    baseStats: { hp: 160, mp: 30, attack: 16, defense: 4 },
    special: 'Êxtase Sangrento: Dano escala com HP faltando.',
    unlockedByDefault: true, color: '#c0392b',
  },
  guardian: {
    name: 'Bastião', emoji: '🗿',
    description: 'Colosso vivo que absorve o dano destinado a seus aliados.',
    baseStats: { hp: 200, mp: 60, attack: 8, defense: 18 },
    special: 'Fortaleza: Reduz 80% do dano do grupo por 2 turnos.',
    unlockedByDefault: true, color: '#7f8c8d',
  },
  druid: {
    name: 'Vidente', emoji: '🌿',
    description: 'Orácolo da floresta primordial que cura, revive e protege.',
    baseStats: { hp: 100, mp: 130, attack: 7, defense: 6 },
    special: 'Renascimento: Restaura 50HP de todos os aliados.',
    unlockedByDefault: true, color: '#27ae60',
  },
  bard: {
    name: 'Trovador', emoji: '🎵',
    description: 'Músico de batalha que inspira o grupo com canções de guerra.',
    baseStats: { hp: 100, mp: 120, attack: 9, defense: 6 },
    special: 'Épico de Combate: +7 ATK, +7 DEF e +30HP para o grupo.',
    unlockedByDefault: true, color: '#d35400',
  },
};

export const SKILLS: Record<ClassType, Skill[]> = {
  warrior: [
    { name: 'Golpe Sagrado',        emoji: '⚔️', mpCost: 0,  damage: 6,  description: '+6 dano bônus' },
    { name: 'Desafio',              emoji: '😤', mpCost: 10, effect: 'taunt',       description: 'Força inimigos a atacar você por 2 turnos' },
    { name: 'Escudo da Fé',         emoji: '🛡️', mpCost: 15, effect: 'defense_up',  defBonus: 8, defBonusTurns: 2, description: '+8 DEF por 2 turnos' },
    { name: 'Punição Divina',       emoji: '💢', mpCost: 30, damage: 20, effect: 'ignore_half_def', description: 'Ignora 50% da DEF, +20 dano' },
    { name: 'Carga Templária',      emoji: '🌪️', mpCost: 20, damage: 8,  aoe: true,  description: 'Ataca TODOS os inimigos (+8 cada)' },
    { name: 'Brado de Guerra',      emoji: '📣', mpCost: 25, effect: 'group_atk_up', atkGroupBonus: 5, atkGroupTurns: 3, description: '+5 ATK para TODOS do grupo por 3 turnos' },
    { name: 'EXTINÇÃO SAGRADA',     emoji: '🌋', mpCost: 100, damage: 60, aoe: true, effect: 'ult', ultLevel: 3,
      ultName: 'EXTINÇÃO SAGRADA',
      ultLines: ['O Templário canaliza a ira dos deuses...', 'O campo de batalha se curva sob seu peso...', 'EXTINÇÃO SAGRADA!'],
      ultColor: '#e74c3c', ultBg: 'radial-gradient(ellipse, #3d0000 0%, #0a0000 70%)',
      description: '🔥 ULT: Explosão devastadora em TODOS. Dano massivo + ignora toda DEF. (Nv.3)' },
  ],
  mage: [
    { name: 'Projétil Arcano',      emoji: '🔥', mpCost: 15, damage: 10, description: '+10 dano arcano' },
    { name: 'Lança de Permafrost',  emoji: '❄️', mpCost: 12, damage: 8,  effect: 'slow',        description: '+8 dano + lentidão (-30% dano) por 2 turnos' },
    { name: 'Barreira Rúnica',      emoji: '🔵', mpCost: 20, effect: 'defense_up', defBonus: 10, defBonusTurns: 2, selfOnly: true, description: '+10 DEF por 2 turnos' },
    { name: 'Colapso Astral',       emoji: '💥', mpCost: 50, damage: 25, aoe: true,  description: 'Dano MASSIVO em todos os inimigos' },
    { name: 'Pulso Relâmpago',      emoji: '⚡', mpCost: 18, damage: 14, description: '+14 dano elétrico' },
    { name: 'Chuva de Cometas',     emoji: '☄️', mpCost: 55, damage: 18, aoe: true,  description: 'Cometas em todos os inimigos' },
    { name: 'APOCALIPSE ARCANO',    emoji: '🌌', mpCost: 100, damage: 80, aoe: true, effect: 'ult', ultLevel: 3,
      ultName: 'APOCALIPSE ARCANO',
      ultLines: ['O Arcanista rompe o véu da realidade...', 'O cosmos entra em colapso sob sua vontade...', 'APOCALIPSE ARCANO!'],
      ultColor: '#9b59b6', ultBg: 'radial-gradient(ellipse, #1a0030 0%, #000008 70%)',
      description: '🔮 ULT: Destrói o tecido da realidade. Dano devastador em área. (Nv.3)' },
  ],
  rogue: [
    { name: 'Punhalada Sombria',    emoji: '🗡️', mpCost: 0,  damage: 5,  description: '+5 dano' },
    { name: 'Inocular',             emoji: '☠️', mpCost: 20, effect: 'poison',   poisonDmg: 10, poisonTurns: 4, description: 'Veneno: 10 dano/turno por 4 turnos' },
    { name: 'Cortina de Fumaça',    emoji: '💨', mpCost: 15, effect: 'dodge',                   description: 'Esquiva dos próximos 2 ataques inimigos' },
    { name: 'Decapitação',          emoji: '⚡', mpCost: 40, damage: 25, effect: 'pierce',       description: '3x dano, ignora TODA a defesa' },
    { name: 'Eco das Sombras',      emoji: '👥', mpCost: 25, damage: 12, description: 'Ataca 2x no mesmo alvo (+12 cada)' },
    { name: 'Fio Envenenado',       emoji: '🐍', mpCost: 35, damage: 10, effect: 'poison', poisonDmg: 12, poisonTurns: 5, description: '+10 dano + veneno (12/t por 5 turnos)' },
    { name: 'ESPIRAL DA MORTE',     emoji: '💀', mpCost: 100, damage: 70, effect: 'ult', ultLevel: 3,
      ultName: 'ESPIRAL DA MORTE',
      ultLines: ['O Espectro dissolve-se nas trevas...', 'Mil lâminas fantasmas cortam o ar...', 'ESPIRAL DA MORTE!'],
      ultColor: '#1abc9c', ultBg: 'radial-gradient(ellipse, #001a15 0%, #000a08 70%)',
      description: '🗡️ ULT: Golpe único que ignora toda DEF + veneno letal. (Nv.3)' },
  ],
  necromancer: [
    { name: 'Pulso Sombrio',        emoji: '🖤', mpCost: 10, damage: 10, description: '+10 dano sombrio' },
    { name: 'Vampirismo',           emoji: '🩸', mpCost: 20, damage: 10, heal: 15,   selfOnly: true, description: '+10 dano, recupera 15HP' },
    { name: 'Praga Profunda',       emoji: '🔮', mpCost: 25, effect: 'curse', curseDef: 5, curseAtk: 4, curseTurns: 4, description: '-5 DEF e -4 ATK no alvo por 4 turnos' },
    { name: 'Legião Sombria',       emoji: '💀', mpCost: 45, effect: 'necro_buff', necroAtkBonus: 8, necroBonusTurns: 5, description: '+8 dano para TODO o grupo por 5 turnos' },
    { name: 'Detonação Sombria',    emoji: '🌑', mpCost: 35, damage: 14, aoe: true,  description: 'Dano sombrio em TODOS os inimigos' },
    { name: 'Toque da Perdição',    emoji: '☠️', mpCost: 55, damage: 25, heal: 18,   selfOnly: true, description: '+25 dano + drena 18HP de volta' },
    { name: 'LEVANTE DAS ALMAS',    emoji: '☠️', mpCost: 100, damage: 50, aoe: true, heal: 40, selfOnly: true, effect: 'ult', ultLevel: 3,
      ultName: 'LEVANTE DAS ALMAS',
      ultLines: ['As almas respondem ao chamado do Ceifador...', 'Exércitos do além emergem das trevas...', 'LEVANTE DAS ALMAS!'],
      ultColor: '#8e44ad', ultBg: 'radial-gradient(ellipse, #1a0028 0%, #050005 70%)',
      description: '💀 ULT: Exército espectral devasta tudo + cura o Ceifador. (Nv.3)' },
  ],
  paladin: [
    { name: 'Veredicto',            emoji: '✨', mpCost: 10, damage: 8,  description: '+8 dano sagrado' },
    { name: 'Imposição de Mãos',    emoji: '💚', mpCost: 20, heal: 35,   targetAlly: true, description: 'Cura 35HP em aliado escolhido' },
    { name: 'Égide Sacra',          emoji: '🌟', mpCost: 25, effect: 'defense_up', defBonus: 12, defBonusTurns: 3, selfOnly: true, description: '+12 DEF por 3 turnos' },
    { name: 'Milagre Sagrado',      emoji: '🙏', mpCost: 60, heal: 40,   effect: 'aoe_heal', description: 'Cura 40HP em TODOS os aliados vivos' },
    { name: 'Martelo da Justiça',   emoji: '🔨', mpCost: 30, damage: 18, description: '+18 dano sagrado' },
    { name: 'Ressurreição',         emoji: '✝️', mpCost: 70, effect: 'revive', reviveHpPct: 0.4, targetAlly: true, description: 'Revive aliado morto com 40% do HP máximo' },
    { name: 'JULGAMENTO FINAL',     emoji: '⚡', mpCost: 100, damage: 55, aoe: true, effect: 'ult', ultLevel: 3,
      heal: 30,
      ultName: 'JULGAMENTO FINAL',
      ultLines: ['A luz dos céus desce sobre o campo de batalha...', 'Nenhuma trevas pode resistir a este clarão...', 'JULGAMENTO FINAL!'],
      ultColor: '#f39c12', ultBg: 'radial-gradient(ellipse, #2a1a00 0%, #0a0600 70%)',
      description: '⚡ ULT: Luz divina destrói todos + cura todo o grupo. (Nv.3)' },
  ],
  ranger: [
    { name: 'Tiro Rápido',          emoji: '🏹', mpCost: 0,  damage: 6,  description: '+6 dano' },
    { name: 'Armadilha de Aço',     emoji: '🪤', mpCost: 20, effect: 'stun',     stunTurns: 2, description: 'Atordoa o alvo por 2 turnos' },
    { name: 'Vista de Falcão',      emoji: '🦅', mpCost: 25, effect: 'aim',      aimBonus: 18, description: 'Próximo ataque básico +18 dano bônus' },
    { name: 'Dilúvio de Flechas',   emoji: '🌧️', mpCost: 45, damage: 12, aoe: true,  description: 'Ataca TODOS os inimigos (+12 cada)' },
    { name: 'Flecha Explosiva',     emoji: '💣', mpCost: 30, damage: 16, description: '+16 dano explosivo' },
    { name: 'Disparo Perfurante',   emoji: '🎯', mpCost: 35, damage: 12, effect: 'pierce', description: 'Ignora TODA a defesa do alvo' },
    { name: 'TEMPESTADE DE FLECHAS',emoji: '🌪️', mpCost: 100, damage: 45, aoe: true, effect: 'ult', ultLevel: 3,
      ultName: 'TEMPESTADE DE FLECHAS',
      ultLines: ['O Caçador mira em todos ao mesmo tempo...', 'O céu escurece com a nuvem de flechas...', 'TEMPESTADE DE FLECHAS!'],
      ultColor: '#3498db', ultBg: 'radial-gradient(ellipse, #001428 0%, #000508 70%)',
      description: '🏹 ULT: Mil flechas caem do céu. Todos os inimigos atordoados. (Nv.3)' },
  ],
  assassin: [
    { name: 'Corte Lunar',          emoji: '🌙', mpCost: 0,  damage: 7,  description: '+7 dano lunar' },
    { name: 'Sentença',             emoji: '🎯', mpCost: 15, effect: 'mark',  markMult: 1.6, markTurns: 3, description: '+60% dano no alvo marcado por 3 turnos' },
    { name: 'Véu das Sombras',      emoji: '🌫️', mpCost: 20, effect: 'dodge',                description: 'Esquiva dos próximos 2 ataques' },
    { name: 'Guilhotina',           emoji: '💀', mpCost: 40, damage: 30, effect: 'execute',   description: '3x dano se alvo < 50% HP (ignora DEF)' },
    { name: 'Rajada Sombria',       emoji: '⚡', mpCost: 25, damage: 15, description: 'Dois golpes rápidos (+15 cada)' },
    { name: 'Toxina Letal',         emoji: '☠️', mpCost: 35, damage: 12, effect: 'poison', poisonDmg: 15, poisonTurns: 5, description: '+12 dano + toxina mortal (15/t por 5t)' },
    { name: 'APAGAMENTO',           emoji: '🌑', mpCost: 100, damage: 90, effect: 'ult', ultLevel: 3,
      ultName: 'APAGAMENTO',
      ultLines: ['A Ombra desaparece da existência...', 'Torna-se uma ferida no tecido do universo...', 'APAGAMENTO!'],
      ultColor: '#2c3e50', ultBg: 'radial-gradient(ellipse, #0a0a0f 0%, #000002 70%)',
      description: '🌑 ULT: Golpe de um ser além das sombras. Dano MÁXIMO em um alvo. (Nv.3)' },
  ],
  elementalist: [
    { name: 'Labaredas',            emoji: '🔥', mpCost: 10, damage: 8,  description: '+8 dano de fogo' },
    { name: 'Dardo de Gelo',        emoji: '❄️', mpCost: 15, damage: 10, effect: 'slow',   description: '+10 dano + lentidão por 2 turnos' },
    { name: 'Descarga Estelar',     emoji: '⚡', mpCost: 18, damage: 14, description: '+14 dano estelar' },
    { name: 'Colapso Tríplice',     emoji: '🌊', mpCost: 55, damage: 20, aoe: true, description: 'Fogo+gelo+raio em TODOS' },
    { name: 'Ventania Glacial',     emoji: '🌨️', mpCost: 30, damage: 10, aoe: true, effect: 'slow', description: 'Gelo+lentidão em TODOS' },
    { name: 'Meteoro de Magma',     emoji: '🌋', mpCost: 45, damage: 30, description: '+30 dano de fogo massivo em 1 alvo' },
    { name: 'CONVERGÊNCIA PRIMORDIAL', emoji: '🌀', mpCost: 100, damage: 65, aoe: true, effect: 'ult', ultLevel: 3,
      ultName: 'CONVERGÊNCIA PRIMORDIAL',
      ultLines: ['O Cataclista canaliza as forças do cosmos...', 'Fogo, gelo, raio e vácuo convergem...', 'CONVERGÊNCIA PRIMORDIAL!'],
      ultColor: '#e67e22', ultBg: 'radial-gradient(ellipse, #1a0f00 0%, #060300 70%)',
      description: '🌀 ULT: Todos os elementos explodem simultaneamente. (Nv.3)' },
  ],
  berserker: [
    { name: 'Machadada',            emoji: '🪓', mpCost: 0,  damage: 8,  description: '+8 dano brutal' },
    { name: 'Êxtase',               emoji: '😡', mpCost: 20, effect: 'berserk', berserkAtkBonus: 8, berserkDefPenalty: 3, berserkTurns: 3, description: '+8 ATK, -3 DEF por 3 turnos' },
    { name: 'Ameaça',               emoji: '🦁', mpCost: 15, effect: 'taunt',   description: 'Força inimigos a atacar você por 2 turnos' },
    { name: 'Devastação',           emoji: '💥', mpCost: 35, damage: 22, effect: 'ignore_half_def', description: 'Ignora 50% da DEF, +22 dano' },
    { name: 'Frenesi Triplo',       emoji: '⚡', mpCost: 25, damage: 10, description: 'Ataca 3x no alvo (+10 cada)' },
    { name: 'Êxtase Sangrento',     emoji: '🩸', mpCost: 45, damage: 20, effect: 'rage_scale', description: 'Dano escala com HP faltando (até 3x se quase morto)' },
    { name: 'FÚRIA DO ABISMO',      emoji: '⚡', mpCost: 100, damage: 75, aoe: true, effect: 'ult', ultLevel: 3,
      ultName: 'FÚRIA DO ABISMO',
      ultLines: ['O Flagelante abandona toda razão...', 'Violência primordial encarnada se liberta...', 'FÚRIA DO ABISMO!'],
      ultColor: '#c0392b', ultBg: 'radial-gradient(ellipse, #280000 0%, #080000 70%)',
      description: '⚡ ULT: Violência absoluta em área, escala com HP perdido. (Nv.3)' },
  ],
  guardian: [
    { name: 'Pancada do Colosso',   emoji: '🗿', mpCost: 0,  damage: 6,  description: '+6 dano com escudo' },
    { name: 'Provocação Absoluta',  emoji: '📢', mpCost: 10, effect: 'taunt', description: 'TODOS os inimigos atacam o Bastião por 2 turnos' },
    { name: 'Fortaleza',            emoji: '🏰', mpCost: 30, effect: 'wall',    wallTurns: 2,    description: 'Reduz 80% do dano de TODOS do grupo por 2 turnos' },
    { name: 'Represália',           emoji: '🔄', mpCost: 25, effect: 'counter', counterPct: 0.6, description: 'Reflete 60% do próximo dano recebido' },
    { name: 'Couraça de Aço',       emoji: '⛩️', mpCost: 20, effect: 'defense_up', defBonus: 20, defBonusTurns: 3, selfOnly: true, description: '+20 DEF por 3 turnos' },
    { name: 'Golpe de Escudo',      emoji: '🛡️', mpCost: 35, damage: 22, effect: 'stun', stunTurns: 1, description: '+22 dano e atordoa o alvo por 1 turno' },
    { name: 'BASTIÃO ETERNO',       emoji: '🗿', mpCost: 100, effect: 'ult', ultLevel: 3,
      ultName: 'BASTIÃO ETERNO',
      ultLines: ['O Bastião torna-se uma montanha viva...', 'Nenhuma força pode mover esta rocha...', 'BASTIÃO ETERNO!'],
      ultColor: '#7f8c8d', ultBg: 'radial-gradient(ellipse, #0f1010 0%, #030404 70%)',
      damage: 30, aoe: true,
      description: '🗿 ULT: Grupo invulnerável por 3 turnos + dano em área. (Nv.3)' },
  ],
  druid: [
    { name: 'Espinhos',             emoji: '🌿', mpCost: 0,  damage: 6,  description: '+6 dano da natureza' },
    { name: 'Toque Vital',          emoji: '🍃', mpCost: 15, heal: 40,   targetAlly: true, description: 'Cura 40HP em aliado escolhido' },
    { name: 'Seiva Regenerativa',   emoji: '♻️', mpCost: 20, effect: 'regen', regenHp: 15, regenTurns: 4, targetAlly: true, description: '+15HP/turno por 4 turnos em aliado' },
    { name: 'Renascimento',         emoji: '🌸', mpCost: 55, heal: 50,   effect: 'aoe_heal', description: 'Cura 50HP em TODOS os aliados vivos' },
    { name: 'Raízes Antigas',       emoji: '🌱', mpCost: 25, effect: 'stun', stunTurns: 2, description: 'Enraíza e atordoa o alvo por 2 turnos' },
    { name: 'Furacão da Floresta',  emoji: '🍂', mpCost: 40, damage: 14, aoe: true, effect: 'poison', poisonDmg: 8, poisonTurns: 3, description: '+14 dano em área + veneno (8/t 3t)' },
    { name: 'DESPERTAR DE GAIA',    emoji: '🌍', mpCost: 100, heal: 80, effect: 'ult', ultLevel: 3,
      ultName: 'DESPERTAR DE GAIA',
      ultLines: ['A terra pulsa com energia ancestral...', 'Gaia responde ao chamado do Vidente...', 'DESPERTAR DE GAIA!'],
      ultColor: '#27ae60', ultBg: 'radial-gradient(ellipse, #001a08 0%, #000503 70%)',
      description: '🌍 ULT: A natureza cura e ressuscita todos os aliados. (Nv.3)' },
  ],
  bard: [
    { name: 'Nota Afiada',          emoji: '🎵', mpCost: 0,  damage: 6,  description: '+6 dano sonoro' },
    { name: 'Canção da Esperança',  emoji: '🎶', mpCost: 15, heal: 30,   targetAlly: true, description: 'Cura 30HP em aliado escolhido' },
    { name: 'Hino do Combate',      emoji: '🎸', mpCost: 20, effect: 'group_atk_up', atkGroupBonus: 5, atkGroupTurns: 3, description: '+5 ATK para TODOS por 3 turnos' },
    { name: 'Épico de Combate',     emoji: '🎺', mpCost: 60, effect: 'balada', baladaAtk: 7, baladaDef: 7, baladaHeal: 30, description: '+7 ATK, +7 DEF e +30HP para TODOS' },
    { name: 'Dissonância Fatal',    emoji: '📯', mpCost: 25, damage: 10, aoe: true,  effect: 'stun', stunTurns: 1, description: 'Som ensurdecedor em todos (+10 dano, 40% atordoar)' },
    { name: 'Réquiem',              emoji: '🎻', mpCost: 45, damage: 22, description: '+22 dano letal' },
    { name: 'SINFONIA DO FIM',      emoji: '🎼', mpCost: 100, effect: 'ult', ultLevel: 3,
      ultName: 'SINFONIA DO FIM',
      ultLines: ['Uma melodia que rasga o próprio mundo...', 'Toda criação treme com o som...', 'SINFONIA DO FIM!'],
      ultColor: '#d35400', ultBg: 'radial-gradient(ellipse, #1a0800 0%, #060200 70%)',
      damage: 40, aoe: true,
      description: '🎼 ULT: A música que destrói mundos. Dano + máximo de buffs. (Nv.3)' },
  ],
};

function makeMonster(
  id: string, name: string, emoji: string, level: number,
  hp: number, attack: number, defense: number,
  xp: number, coins: number, isBoss = false,
  extras: Partial<Monster> = {}
): Monster {
  return { id, name, emoji, level, hp, maxHp: hp, attack, defense, xpReward: xp, coinReward: coins, isBoss, effects: [], ...extras };
}

export const MAPS: MapDefinition[] = [
  // ── MAP 1 ──────────────────────────────────────────────────────────────────
  {
    id: 1, name: 'Vale dos Condenados', theme: '🌲',
    description: 'Um vale esquecido onde os mortos não descansam.',
    difficulty: 'Iniciante', defenseDebuff: 0, manaCostMultiplier: 1, bgColor: '#1a2f1a', unlocked: true,
    monsters: [
      makeMonster('renegade',   'Renegado',          '🧟', 1, 45, 7, 2, 15, 5),
      makeMonster('wolf',       'Lobo Cinzento',     '🐺', 1, 40, 8, 3, 12, 4),
      makeMonster('plagued',    'Infectado',         '🧪', 1, 38, 6, 1, 10, 3),
      makeMonster('cultist',    'Cultista',          '🪬', 1, 42, 7, 2, 14, 4),
      makeMonster('deserter',   'Desertor',          '⚔️', 1, 50, 8, 2, 16, 6),
    ],
    boss: makeMonster('warlord', 'Senhor da Guerra', '👹', 3, 420, 16, 8, 100, 40, true, {
      multiAttack: 1,
      enrageThreshold: 0.5,
      enrageAtkBonus: 6,
      splashChance: 0.2,
      bossUlt: {
        name: 'GOLPE DEVASTADOR',
        emoji: '👊',
        description: 'Esmaga o grupo inteiro com força brutal!',
        aoeDamage: 22,
        lines: ['O Senhor da Guerra ergue seu maçaço...', 'O solo racha sob o impacto...', 'GOLPE DEVASTADOR!'],
        color: '#e74c3c',
        bg: 'radial-gradient(ellipse, #2a0000 0%, #080000 70%)',
      },
      ultCooldown: 4, ultTurnsLeft: 4,
    }),
  },
  // ── MAP 2 ──────────────────────────────────────────────────────────────────
  {
    id: 2, name: 'Pântano da Pestilência', theme: '🌿',
    description: 'Águas podres que corrompem tudo que tocam.',
    difficulty: 'Iniciante', defenseDebuff: 0, manaCostMultiplier: 1, bgColor: '#1a2a10', unlocked: false,
    monsters: [
      makeMonster('toadfiend',   'Sapo Pestilento',  '🐸', 3, 65, 12, 3, 20, 7),
      makeMonster('vipera',      'Víbora Pútrida',   '🐍', 3, 60, 13, 2, 18, 6),
      makeMonster('blightshroom','Fungo Corrompido', '🍄', 3, 72, 10, 4, 22, 8),
      makeMonster('miredrake',   'Draque do Lodaçal','🦎', 3, 68, 12, 3, 21, 7),
    ],
    boss: makeMonster('plaguemother', 'Mãe da Pestilência', '🐲', 5, 620, 20, 10, 150, 55, true, {
      multiAttack: 2,
      enrageThreshold: 0.4,
      enrageAtkBonus: 8,
      regenPerTurn: 15,
      splashChance: 0.35,
      bossUlt: {
        name: 'NÉVOA DA MORTE',
        emoji: '☠️',
        description: 'Pestilência tóxica envolve todo o grupo!',
        aoeDamage: 28,
        lines: ['A Mãe da Pestilência abre sua mandíbula tríplice...', 'Uma névoa pútrida preenche o ar...', 'NÉVOA DA MORTE!'],
        color: '#27ae60',
        bg: 'radial-gradient(ellipse, #001a08 0%, #000503 70%)',
      },
      ultCooldown: 4, ultTurnsLeft: 4,
    }),
  },
  // ── MAP 3 ──────────────────────────────────────────────────────────────────
  {
    id: 3, name: 'Catacumbas Profundas', theme: '🪨',
    description: 'Túneis sem fim onde a luz nunca chegou. Defesa -20%!',
    difficulty: 'Intermediário', defenseDebuff: 0.2, manaCostMultiplier: 1, bgColor: '#1a1a2f', unlocked: false,
    monsters: [
      makeMonster('marauder',   'Marauder',           '🧌', 6, 120, 17, 8,  50, 18),
      makeMonster('stonewraith','Espectro Pétreo',    '🪨', 6, 145, 15, 13, 55, 20),
      makeMonster('darkblade',  'Lâmina das Trevas',  '🧝', 6, 100, 19, 5,  48, 17),
      makeMonster('tombcrawler','Rastejador de Tumbas','🦇', 6, 90,  18, 4,  42, 15),
      makeMonster('ironbrute',  'Brutamontes Ferroso','👾', 6, 130, 17, 7,  52, 19),
    ],
    boss: makeMonster('stonelord', 'Senhor das Pedras', '⛏️', 7, 850, 26, 20, 220, 85, true, {
      multiAttack: 2,
      enrageThreshold: 0.45,
      enrageAtkBonus: 10,
      armorPierce: 0.4,
      regenPerTurn: 20,
      bossUlt: {
        name: 'COLAPSO DAS CATACUMBAS',
        emoji: '🌍',
        description: 'O teto das catacumbas desmorona sobre o grupo!',
        aoeDamage: 35,
        removeAllDebuffs: true,
        lines: ['O Senhor das Pedras bate seus punhos no chão...', 'As paredes começam a rachar e cair...', 'COLAPSO DAS CATACUMBAS!'],
        color: '#7f8c8d',
        bg: 'radial-gradient(ellipse, #0f1010 0%, #030404 70%)',
      },
      ultCooldown: 3, ultTurnsLeft: 3,
    }),
  },
  // ── MAP 4 ──────────────────────────────────────────────────────────────────
  {
    id: 4, name: 'Cidade Fantasma', theme: '🏚️',
    description: 'Uma metrópole abandonada habitada por espíritos torturados.',
    difficulty: 'Intermediário', defenseDebuff: 0.1, manaCostMultiplier: 1, bgColor: '#2a1a2f', unlocked: false,
    monsters: [
      makeMonster('poltergeist', 'Poltergeist',         '👻', 8, 115, 22, 4,  60, 22),
      makeMonster('revenant',    'Revenante',           '💀', 8, 140, 20, 8,  65, 24),
      makeMonster('corpsemob',   'Turba de Cadáveres',  '🧟', 8, 165, 18, 7,  62, 23),
      makeMonster('shadowfiend', 'Demônio da Sombra',   '🌑', 8, 120, 24, 5,  68, 25),
    ],
    boss: makeMonster('phantom_king', 'Rei Fantasma', '☠️', 9, 1050, 32, 16, 320, 120, true, {
      multiAttack: 2,
      enrageThreshold: 0.5,
      enrageAtkBonus: 14,
      armorPierce: 0.3,
      splashChance: 0.4,
      bossUlt: {
        name: 'MALDIÇÃO DA CIDADE MORTA',
        emoji: '🔮',
        description: 'A maldição ancestral da cidade drena a força vital de todos!',
        aoeDamage: 42,
        buffAtk: 8,
        buffAtkTurns: 3,
        lines: ['O Rei Fantasma ergue seu cetro espectral...', 'A maldição da cidade morta é invocada...', 'MALDIÇÃO DA CIDADE MORTA!'],
        color: '#8e44ad',
        bg: 'radial-gradient(ellipse, #1a0028 0%, #050005 70%)',
      },
      ultCooldown: 3, ultTurnsLeft: 3,
    }),
  },
  // ── MAP 5 ──────────────────────────────────────────────────────────────────
  {
    id: 5, name: 'Caldeira do Inferno', theme: '🌋',
    description: 'Calor que derrete o aço. Custo de mana dobrado!',
    difficulty: 'Avançado', defenseDebuff: 0, manaCostMultiplier: 2, bgColor: '#2f1510', unlocked: false,
    monsters: [
      makeMonster('emberspawn',  'Nascido da Brasa',  '🔥', 10, 175, 28, 12, 90, 35),
      makeMonster('magmagolem',  'Golem de Magma',    '🌋', 10, 210, 25, 17, 95, 38),
      makeMonster('cinderwing',  'Asa de Cinza',      '🐉', 10, 190, 30, 13, 92, 36),
      makeMonster('infernum',    'Infernão',          '✨', 10, 155, 32, 8,  88, 34),
    ],
    boss: makeMonster('volcanus', 'Volcanus, o Incinerador', '🔴', 11, 1400, 38, 22, 450, 175, true, {
      multiAttack: 3,
      enrageThreshold: 0.45,
      enrageAtkBonus: 18,
      armorPierce: 0.5,
      regenPerTurn: 30,
      splashChance: 0.5,
      bossUlt: {
        name: 'ERUPÇÃO DO FIM',
        emoji: '🌋',
        description: 'A caldeira inteira explode sobre o grupo!',
        aoeDamage: 55,
        removeAllDebuffs: true,
        buffAtk: 15,
        buffAtkTurns: 2,
        lines: ['Volcanus mergulha no magma...', 'A caldeira inteira entra em erupção de uma vez!', 'ERUPÇÃO DO FIM!'],
        color: '#e74c3c',
        bg: 'radial-gradient(ellipse, #3d0000 0%, #0a0000 70%)',
      },
      ultCooldown: 3, ultTurnsLeft: 3,
    }),
  },
  // ── MAP 6 ──────────────────────────────────────────────────────────────────
  {
    id: 6, name: 'Cidadela Abissal', theme: '🏰',
    description: 'Fortaleza dos condenados. Mana dobrada.',
    difficulty: 'Avançado', defenseDebuff: 0, manaCostMultiplier: 2, bgColor: '#2f1a1a', unlocked: false,
    monsters: [
      makeMonster('voidknight',  'Cavaleiro do Vazio',   '😈', 12, 235, 33, 17, 110, 45),
      makeMonster('soulbinder',  'Acorrentador de Almas','💀', 12, 205, 36, 12, 115, 48),
      makeMonster('abyssdrake',  'Drake Abissal',        '🐉', 12, 260, 30, 19, 120, 50),
      makeMonster('dreadlord',   'Senhor do Terror',     '🖤', 12, 245, 34, 18, 118, 47),
    ],
    boss: makeMonster('abyss_sovereign', 'Soberano do Abismo', '👿', 13, 1800, 44, 25, 650, 260, true, {
      multiAttack: 3,
      enrageThreshold: 0.4,
      enrageAtkBonus: 22,
      armorPierce: 0.55,
      regenPerTurn: 40,
      splashChance: 0.55,
      bossUlt: {
        name: 'COLAPSO DO ABISMO',
        emoji: '👿',
        description: 'O abismo engole tudo ao redor!',
        aoeDamage: 68,
        healSelf: 200,
        buffAtk: 18,
        buffAtkTurns: 3,
        lines: ['O Soberano do Abismo abre uma fenda dimensional...', 'O abismo consome tudo sem piedade...', 'COLAPSO DO ABISMO!'],
        color: '#c0392b',
        bg: 'radial-gradient(ellipse, #280000 0%, #080000 70%)',
      },
      ultCooldown: 3, ultTurnsLeft: 3,
    }),
  },
  // ── MAP 7 ──────────────────────────────────────────────────────────────────
  {
    id: 7, name: 'Trono dos Deuses Caídos', theme: '⚡',
    description: 'Onde os deuses morreram. Defesa -30%, mana x2.',
    difficulty: 'Lendário', defenseDebuff: 0.3, manaCostMultiplier: 2, bgColor: '#1a1030', unlocked: false,
    monsters: [
      makeMonster('fallenone',   'O Caído',           '🪽', 16, 355, 42, 22, 180, 72),
      makeMonster('voidborn',    'Nascido do Vazio',  '🌀', 16, 390, 40, 25, 185, 74),
      makeMonster('oblivionis',  'Ceifador Eterno',   '🌑', 16, 320, 46, 20, 190, 76),
      makeMonster('titanspawn',  'Prole de Titã',     '👁️', 16, 368, 41, 26, 182, 73),
    ],
    boss: makeMonster('fallen_god', 'Deus Corrompido', '🌟', 20, 3200, 58, 32, 1500, 600, true, {
      multiAttack: 3,
      enrageThreshold: 0.45,
      enrageAtkBonus: 28,
      armorPierce: 0.6,
      regenPerTurn: 60,
      splashChance: 0.6,
      bossUlt: {
        name: 'IRA DO DEUS MORTO',
        emoji: '⚡',
        description: 'O poder divino corrompido destrói a realidade!',
        aoeDamage: 85,
        healSelf: 350,
        removeAllDebuffs: true,
        buffAtk: 24,
        buffAtkTurns: 3,
        lines: ['O Deus Corrompido libera séculos de fúria...', 'A realidade se curva sob seu olhar morto...', 'IRA DO DEUS MORTO!'],
        color: '#f0c040',
        bg: 'radial-gradient(ellipse, #2a1a00 0%, #0a0600 70%)',
      },
      ultCooldown: 3, ultTurnsLeft: 3,
    }),
  },
  // ── MAP 8 ──────────────────────────────────────────────────────────────────
  {
    id: 8, name: 'Necrópole Eterna', theme: '🪦',
    description: 'A maior necrópole do mundo. Defesa -40%, mana x2.',
    difficulty: 'Infernal', defenseDebuff: 0.4, manaCostMultiplier: 2, bgColor: '#150a20', unlocked: false,
    monsters: [
      makeMonster('deathknight',   'Cavaleiro da Morte',  '💀', 20, 440, 52, 28, 250, 100),
      makeMonster('bloodlord',     'Senhor do Sangue',    '🧛', 20, 400, 56, 22, 260, 105),
      makeMonster('bonedrake',     'Drake Ósseo',         '🦴', 20, 480, 50, 30, 255, 102),
      makeMonster('wailsinger',    'Cantora dos Lamentos','👁️', 20, 380, 58, 18, 245, 98),
    ],
    boss: makeMonster('lich_emperor', 'Imperador-Lich', '👑', 24, 4200, 70, 38, 2000, 800, true, {
      multiAttack: 4,
      enrageThreshold: 0.5,
      enrageAtkBonus: 35,
      armorPierce: 0.65,
      regenPerTurn: 80,
      splashChance: 0.65,
      bossUlt: {
        name: 'EXTINÇÃO DOS VIVOS',
        emoji: '💀',
        description: 'O Imperador-Lich decreta o fim de toda vida!',
        aoeDamage: 100,
        healSelf: 400,
        removeAllDebuffs: true,
        buffAtk: 30,
        buffAtkTurns: 4,
        lines: ['O Imperador-Lich abre os portais da morte eterna...', 'Mil almas gritam em uníssono...', 'EXTINÇÃO DOS VIVOS!'],
        color: '#8e44ad',
        bg: 'radial-gradient(ellipse, #1a0028 0%, #050005 70%)',
      },
      ultCooldown: 3, ultTurnsLeft: 3,
    }),
  },
  // ── MAP 9 ──────────────────────────────────────────────────────────────────
  {
    id: 9, name: 'Fracturas do Cosmos', theme: '🌌',
    description: 'Onde o universo se rasgou. Defesa -35%, mana x3.',
    difficulty: 'Infernal', defenseDebuff: 0.35, manaCostMultiplier: 3, bgColor: '#050515', unlocked: false,
    monsters: [
      makeMonster('voidhorror',   'Horror do Vazio',     '🌀', 24, 520, 62, 32, 320, 130),
      makeMonster('starborn',     'Nascido das Estrelas','⭐', 24, 480, 66, 26, 330, 132),
      makeMonster('ancientthing', 'Coisa Antiga',        '👾', 24, 560, 60, 34, 315, 128),
      makeMonster('voidleech',    'Sanguessuga do Vazio','🪱', 24, 450, 68, 24, 335, 134),
    ],
    boss: makeMonster('cosmos_ender', 'O Fim do Cosmos', '🌌', 28, 5500, 82, 44, 2800, 1100, true, {
      multiAttack: 4,
      enrageThreshold: 0.5,
      enrageAtkBonus: 42,
      armorPierce: 0.7,
      regenPerTurn: 100,
      splashChance: 0.7,
      bossUlt: {
        name: 'COLAPSO GRAVITACIONAL',
        emoji: '🌌',
        description: 'A gravidade do cosmos esmaga toda a existência!',
        aoeDamage: 120,
        healSelf: 500,
        removeAllDebuffs: true,
        buffAtk: 38,
        buffAtkTurns: 4,
        lines: ['O Fim do Cosmos dobra o espaço ao redor...', 'Um buraco negro se materializa no campo de batalha...', 'COLAPSO GRAVITACIONAL!'],
        color: '#9b59b6',
        bg: 'radial-gradient(ellipse, #05000f 0%, #000002 70%)',
      },
      ultCooldown: 3, ultTurnsLeft: 3,
    }),
  },
  // ── MAP 10 ─────────────────────────────────────────────────────────────────
  {
    id: 10, name: 'Forja dos Titãs', theme: '⚒️',
    description: 'Onde os Titãs nascem. Defesa -40%, mana x3.',
    difficulty: 'Infernal', defenseDebuff: 0.4, manaCostMultiplier: 3, bgColor: '#201008', unlocked: false,
    monsters: [
      makeMonster('irontitan',   'Titã de Ferro',     '⚙️', 28, 620, 72, 40, 400, 160),
      makeMonster('flamewarden', 'Guardião da Chama', '🔥', 28, 580, 78, 34, 410, 164),
      makeMonster('stormtitan',  'Titã da Tempestade','⚡', 28, 600, 74, 38, 405, 162),
      makeMonster('earthrend',   'Rasgador da Terra', '🪨', 28, 660, 70, 44, 395, 158),
    ],
    boss: makeMonster('prime_titan', 'Titã Primordial', '⚒️', 32, 7000, 95, 52, 3500, 1400, true, {
      multiAttack: 4,
      enrageThreshold: 0.5,
      enrageAtkBonus: 50,
      armorPierce: 0.75,
      regenPerTurn: 130,
      splashChance: 0.75,
      bossUlt: {
        name: 'FORJA DA EXTINÇÃO',
        emoji: '⚒️',
        description: 'O calor da criação destrói toda a existência!',
        aoeDamage: 145,
        healSelf: 650,
        removeAllDebuffs: true,
        buffAtk: 45,
        buffAtkTurns: 4,
        lines: ['O Titã Primordial aquece sua forja cósmica...', 'Metal e fogo se fundem num único ser...', 'FORJA DA EXTINÇÃO!'],
        color: '#e67e22',
        bg: 'radial-gradient(ellipse, #1a0f00 0%, #060300 70%)',
      },
      ultCooldown: 2, ultTurnsLeft: 2,
    }),
  },
  // ── MAP 11 ─────────────────────────────────────────────────────────────────
  {
    id: 11, name: 'Empíreo Corrompido', theme: '😇',
    description: 'O paraíso que virou trevas. Defesa -50%, mana x3.',
    difficulty: 'Divino', defenseDebuff: 0.5, manaCostMultiplier: 3, bgColor: '#0a0a20', unlocked: false,
    monsters: [
      makeMonster('fallenarch',  'Arcanjo Caído',    '😇', 32, 720, 88, 46, 500, 200),
      makeMonster('darkseraph',  'Serafim das Trevas','🖤', 32, 680, 94, 40, 510, 204),
      makeMonster('blightgod',   'Deus da Corrupção','👁️', 32, 760, 86, 50, 495, 198),
      makeMonster('voidangel',   'Anjo do Oblívio',  '🌑', 32, 700, 96, 42, 515, 206),
    ],
    boss: makeMonster('void_seraph', 'Serafim do Oblívio', '😈', 36, 9000, 112, 62, 5000, 2000, true, {
      multiAttack: 4,
      enrageThreshold: 0.5,
      enrageAtkBonus: 60,
      armorPierce: 0.8,
      regenPerTurn: 170,
      splashChance: 0.8,
      bossUlt: {
        name: 'EXTINÇÃO CELESTE',
        emoji: '😈',
        description: 'A luz corrompida extermina toda a existência!',
        aoeDamage: 175,
        healSelf: 900,
        removeAllDebuffs: true,
        buffAtk: 55,
        buffAtkTurns: 5,
        lines: ['O Serafim do Oblívio estende suas asas negras...', 'A luz e as trevas colidem no ponto singular...', 'EXTINÇÃO CELESTE!'],
        color: '#f39c12',
        bg: 'radial-gradient(ellipse, #2a1a00 0%, #0a0600 70%)',
      },
      ultCooldown: 2, ultTurnsLeft: 2,
    }),
  },
  // ── MAP 12 ─────────────────────────────────────────────────────────────────
  {
    id: 12, name: 'O Fim de Tudo', theme: '🌑',
    description: '⚠️ BOSS FINAL: Defesa -60%, mana x3. A ameaça que destruiu os deuses.',
    difficulty: 'Divino', defenseDebuff: 0.6, manaCostMultiplier: 3, bgColor: '#000000', unlocked: false,
    monsters: [
      makeMonster('oblivishadow', 'Sombra do Oblívio',    '🌑', 36, 850, 105, 55, 650, 260),
      makeMonster('entropywraith','Espectro da Entropia', '🌀', 36, 800, 112, 48, 660, 264),
      makeMonster('voidslayer',   'Destruidor do Vazio',  '💀', 36, 900, 100, 60, 645, 258),
      makeMonster('nihilcoloss',  'Colosso do Nada',      '👁️', 36, 920, 108, 58, 655, 262),
    ],
    boss: makeMonster('the_end', 'O FIM', '💫', 40, 14000, 140, 75, 10000, 4000, true, {
      multiAttack: 5,
      enrageThreshold: 0.5,
      enrageAtkBonus: 80,
      armorPierce: 0.85,
      regenPerTurn: 250,
      splashChance: 0.85,
      bossUlt: {
        name: 'ANIQUILAÇÃO ABSOLUTA',
        emoji: '💫',
        description: 'O vazio absoluto apaga toda a existência!',
        aoeDamage: 230,
        healSelf: 1500,
        removeAllDebuffs: true,
        buffAtk: 70,
        buffAtkTurns: 5,
        enrageMultiplier: 1.3,
        lines: ['O FIM abre seus olhos pela primeira vez...', 'Toda a existência geme sob seu olhar...', 'ANIQUILAÇÃO ABSOLUTA!'],
        color: '#9b59b6',
        bg: 'radial-gradient(ellipse, #050005 0%, #000000 70%)',
      },
      ultCooldown: 2, ultTurnsLeft: 2,
    }),
  },
];

export const SHOP_ITEMS: Item[] = [
  // ── POTIONS ──
  { id: 'potion_hp_s',  name: 'Erva Curativa',      emoji: '🧪', price: 20,  attackBonus: 0, defenseBonus: 0, consumable: true, consumeHeal: 50,   quantity: 2, description: '+50 HP (2 usos)' },
  { id: 'potion_hp_m',  name: 'Decocto de Cura',    emoji: '💊', price: 40,  attackBonus: 0, defenseBonus: 0, consumable: true, consumeHeal: 90,   quantity: 2, description: '+90 HP (2 usos)' },
  { id: 'potion_hp_l',  name: 'Elixir de Vida',     emoji: '⚗️', price: 80,  attackBonus: 0, defenseBonus: 0, consumable: true, consumeHeal: 160,  quantity: 2, description: '+160 HP (2 usos)' },
  { id: 'potion_hp_xl', name: 'Elixir Divino',      emoji: '🌹', price: 160, attackBonus: 0, defenseBonus: 0, consumable: true, consumeHeal: 320,  quantity: 2, description: '+320 HP (2 usos)' },
  { id: 'potion_mp_s',  name: 'Cristal de Mana',    emoji: '💧', price: 20,  attackBonus: 0, defenseBonus: 0, consumable: true, consumeMpHeal: 40,  quantity: 2, description: '+40 MP (2 usos)' },
  { id: 'potion_mp_m',  name: 'Essência Arcana',    emoji: '🫧', price: 40,  attackBonus: 0, defenseBonus: 0, consumable: true, consumeMpHeal: 80,  quantity: 2, description: '+80 MP (2 usos)' },
  { id: 'potion_mp_l',  name: 'Reservatório Mágico',emoji: '💙', price: 90,  attackBonus: 0, defenseBonus: 0, consumable: true, consumeMpHeal: 160, quantity: 2, description: '+160 MP (2 usos)' },
  { id: 'potion_full',  name: 'Elixir Duplo',        emoji: '🌟', price: 100, attackBonus: 0, defenseBonus: 0, consumable: true, consumeHeal: 120, consumeMpHeal: 120, quantity: 1, description: '+120 HP e +120 MP (1 uso)' },
  { id: 'potion_ultra', name: 'Elixir dos Imortais', emoji: '✨', price: 250, attackBonus: 0, defenseBonus: 0, consumable: true, consumeHeal: 400, consumeMpHeal: 300, quantity: 1, description: '+400 HP e +300 MP (1 uso)' },
  // ── BASIC GEAR ──
  { id: 'iron_sword',     name: 'Lâmina de Ferro',      emoji: '⚔️', price: 30,  attackBonus: 6,  defenseBonus: 0,  description: '+6 ATK',         permanent: true },
  { id: 'steel_shield',   name: 'Escudo de Aço',         emoji: '🛡️', price: 30,  attackBonus: 0,  defenseBonus: 6,  description: '+6 DEF',         permanent: true },
  { id: 'health_stone',   name: 'Runa Vital',             emoji: '❤️', price: 40,  attackBonus: 0,  defenseBonus: 0,  hpBonus: 40,  description: '+40 HP Máx',    permanent: true },
  { id: 'mana_crystal',   name: 'Pedra Arcana',           emoji: '💎', price: 40,  attackBonus: 0,  defenseBonus: 0,  mpBonus: 40,  description: '+40 MP Máx',    permanent: true },
  { id: 'magic_ring',     name: 'Anel do Combatente',     emoji: '💍', price: 55,  attackBonus: 4,  defenseBonus: 4,  description: '+4 ATK +4 DEF',  permanent: true },
  { id: 'amulet',         name: 'Amuleto da Sobrevivência',emoji: '📿', price: 65, attackBonus: 5,  defenseBonus: 5,  description: '+5 ATK +5 DEF',  permanent: true },
  { id: 'war_boots',      name: 'Botas da Batalha',       emoji: '👢', price: 55,  attackBonus: 5,  defenseBonus: 3,  description: '+5 ATK +3 DEF',  permanent: true },
  { id: 'mystic_orb',     name: 'Orbe do Arcanista',      emoji: '🔮', price: 65,  attackBonus: 7,  defenseBonus: 0,  mpBonus: 25,  description: '+7 ATK +25 MP', permanent: true },
  // ── ADVANCED GEAR ──
  { id: 'dragon_scale',    name: 'Escama de Wyrm',         emoji: '🐉', price: 85,  attackBonus: 0,  defenseBonus: 12, description: '+12 DEF',        permanent: true },
  { id: 'enchanted_blade', name: 'Lâmina Encantada',       emoji: '✨', price: 85,  attackBonus: 12, defenseBonus: 0,  description: '+12 ATK',        permanent: true },
  { id: 'arcane_tome',     name: 'Grimório Proibido',       emoji: '📖', price: 110, attackBonus: 10, defenseBonus: 0,  mpBonus: 50,  description: '+10 ATK +50 MP', permanent: true },
  { id: 'elixir_life',     name: 'Coração de Pedra',        emoji: '💠', price: 110, attackBonus: 0,  defenseBonus: 6,  hpBonus: 70,  description: '+70 HP +6 DEF',  permanent: true },
  { id: 'titan_armor',     name: 'Armadura do Colosso',     emoji: '🦺', price: 130, attackBonus: 3,  defenseBonus: 18, description: '+3 ATK +18 DEF', permanent: true },
  { id: 'void_blade',      name: 'Lâmina do Oblívio',       emoji: '🌑', price: 130, attackBonus: 18, defenseBonus: 0,  description: '+18 ATK',        permanent: true },
  { id: 'godslayer',       name: 'Deicida',                 emoji: '🗡️', price: 200, attackBonus: 24, defenseBonus: 6,  description: '+24 ATK +6 DEF', permanent: true },
  { id: 'divine_shield',   name: 'Escudo Sagrado',          emoji: '🌟', price: 200, attackBonus: 6,  defenseBonus: 24, hpBonus: 40, description: '+6 ATK +24 DEF +40 HP', permanent: true },
  // ── LEGENDARY GEAR ──
  { id: 'abyssal_crown',   name: 'Coroa do Abismo',         emoji: '👑', price: 280, attackBonus: 30, defenseBonus: 10, description: '+30 ATK +10 DEF',            permanent: true },
  { id: 'celestial_armor', name: 'Armadura Celestial',      emoji: '🌈', price: 280, attackBonus: 10, defenseBonus: 32, hpBonus: 60, description: '+10 ATK +32 DEF +60 HP', permanent: true },
  { id: 'cosmic_staff',    name: 'Cajado Cósmico',          emoji: '🌌', price: 300, attackBonus: 28, defenseBonus: 0,  mpBonus: 100, description: '+28 ATK +100 MP',        permanent: true },
  { id: 'lifestone_heart', name: 'Coração de Pedra Viva',   emoji: '💗', price: 300, attackBonus: 0,  defenseBonus: 12, hpBonus: 140, description: '+140 HP +12 DEF',        permanent: true },
  { id: 'void_relic',      name: 'Relíquia do Oblívio',     emoji: '🔯', price: 350, attackBonus: 32, defenseBonus: 14, hpBonus: 50, mpBonus: 60, description: '+32 ATK +14 DEF +50HP +60MP', permanent: true },
  { id: 'oblivion_blade',  name: 'Lâmina da Extinção',      emoji: '⚫', price: 400, attackBonus: 40, defenseBonus: 8,  description: '+40 ATK +8 DEF',             permanent: true },
  { id: 'god_bastion',     name: 'Bastião dos Imortais',    emoji: '🏛️', price: 400, attackBonus: 8,  defenseBonus: 42, hpBonus: 80, description: '+8 ATK +42 DEF +80 HP', permanent: true },
  { id: 'annihilator',     name: 'O Aniquilador',           emoji: '💥', price: 500, attackBonus: 50, defenseBonus: 15, hpBonus: 60, description: '+50 ATK +15 DEF +60 HP', permanent: true },
  { id: 'eternity_ring',   name: 'Anel da Eternidade',      emoji: '♾️', price: 500, attackBonus: 20, defenseBonus: 20, hpBonus: 100, mpBonus: 100, description: '+20/20 ATK/DEF +100 HP/MP', permanent: true },
];

export const XP_PER_LEVEL = (level: number) => level * 100;

export function createPlayer(id: string, name: string, classType: ClassType): Player {
  const cls = CLASSES[classType];
  return {
    id, name, classType,
    level: 1, xp: 0, xpToNextLevel: 100,
    hp: cls.baseStats.hp, maxHp: cls.baseStats.hp,
    mp: cls.baseStats.mp, maxMp: cls.baseStats.mp,
    attack: cls.baseStats.attack, defense: cls.baseStats.defense,
    baseAttack: cls.baseStats.attack,
    baseDefense: cls.baseStats.defense,
    inventory: [], coins: 0, isReady: false, isAlive: true,
    statusEffects: [],
    buffs: { ...DEFAULT_BUFFS },
  };
}

export function rollDice(): number {
  return Math.floor(Math.random() * 10) + 1;
}

export function calculateDamage(attackerAttack: number, targetDefense: number, diceRoll: number, bonus = 0): number {
  return Math.max(1, diceRoll + attackerAttack + bonus - targetDefense);
}

export function levelUp(player: Player): { player: Player; didLevelUp: boolean } {
  if (player.xp < player.xpToNextLevel) return { player, didLevelUp: false };
  const newLevel = player.level + 1;
  const hpGain = 18;
  const mpGain = 12;
  return {
    player: {
      ...player,
      level: newLevel,
      xp: player.xp - player.xpToNextLevel,
      xpToNextLevel: XP_PER_LEVEL(newLevel),
      maxHp: player.maxHp + hpGain,
      hp: Math.min(player.hp + hpGain, player.maxHp + hpGain),
      maxMp: player.maxMp + mpGain,
      attack: player.baseAttack + Math.floor(newLevel * 1.8) + (player.attack - player.baseAttack - Math.floor(player.level * 1.8)),
      defense: player.baseDefense + Math.floor(newLevel * 1.0) + (player.defense - player.baseDefense - Math.floor(player.level * 1.0)),
    },
    didLevelUp: true,
  };
}