import { ClassType, TransformDefinition } from './types';

export const TRANSFORMS: Record<ClassType, TransformDefinition> = {
  warrior: {
    name: 'Colossus Sagrado',
    emoji: '🔥⚔️',
    description: 'O Templário transcende os limites da carne. Seu corpo torna-se aço incandescente.',
    atkMultiplier: 2.2,
    defMultiplier: 2.0,
    hpBonusFlat: 80,
    ultLines: ['O Templário absorve a essência do Deus Corrompido...', 'Seus músculos tornam-se aço vivo...', 'COLOSSUS SAGRADO!'],
    ultColor: '#ff4400',
    ultBg: 'radial-gradient(ellipse, #3d0800 0%, #0a0000 70%)',
    skillOverrides: [
      { name: 'Golpe Divino',          emoji: '⚔️🔥', mpCost: 0,  damage: 18, description: '+18 dano divino' },
      { name: 'Punição Absoluta',      emoji: '💢🌋', mpCost: 20, damage: 35, description: 'Ignora toda DEF, +35 dano' },
      { name: 'Égide de Aço',          emoji: '🛡️🔥', mpCost: 15, effect: 'defense_up', defBonus: 20, defBonusTurns: 3, description: '+20 DEF por 3 turnos' },
      { name: 'Carga Devastadora',     emoji: '🌪️💥', mpCost: 30, damage: 28, aoe: true, description: '+28 dano em TODOS' },
      { name: 'Brado Divino',          emoji: '📣⚡', mpCost: 20, effect: 'group_atk_up', atkGroupBonus: 12, atkGroupTurns: 4, description: '+12 ATK para TODO o grupo por 4t' },
      { name: 'Impacto do Colossus',   emoji: '🌋💀', mpCost: 50, damage: 60, aoe: true, description: '60 dano em todos, ignora DEF' },
      { name: 'EXTINÇÃO DIVINA',       emoji: '☄️⚔️', mpCost: 120, damage: 100, aoe: true, effect: 'ult', ultLevel: 1,
        ultName: 'EXTINÇÃO DIVINA',
        ultLines: ['O Colossus libera toda a força do Deus Corrompido...', 'O campo de batalha é varrido da existência...', 'EXTINÇÃO DIVINA!'],
        ultColor: '#ff4400', ultBg: 'radial-gradient(ellipse, #4d1000 0%, #0a0000 70%)',
        description: '🌋 ULT DIVINA: 100 dano em TODOS + atordoa.' },
    ],
  },
  mage: {
    name: 'Arcanista Supremo',
    emoji: '🌌🔮',
    description: 'O Arcanista transcende as leis da magia. O cosmos obedece sua vontade.',
    atkMultiplier: 2.5,
    defMultiplier: 1.5,
    hpBonusFlat: 40,
    ultLines: ['O Arcanista absorve o conhecimento do Deus Corrompido...', 'O cosmos se dobra à sua vontade...', 'ARCANISTA SUPREMO!'],
    ultColor: '#cc00ff',
    ultBg: 'radial-gradient(ellipse, #1a0035 0%, #000008 70%)',
    skillOverrides: [
      { name: 'Chama Cósmica',         emoji: '🌌🔥', mpCost: 0,  damage: 22, description: '+22 dano cósmico' },
      { name: 'Colapso Dimensional',   emoji: '🌀💥', mpCost: 25, damage: 40, description: '+40 dano, ignora DEF' },
      { name: 'Escudo do Cosmos',      emoji: '🔵🌌', mpCost: 20, effect: 'defense_up', defBonus: 18, defBonusTurns: 3, selfOnly: true, description: '+18 DEF por 3 turnos' },
      { name: 'Nova Estelar',          emoji: '⭐💥', mpCost: 45, damage: 45, aoe: true, description: '+45 dano em TODOS' },
      { name: 'Pulso do Fim',          emoji: '⚡🌌', mpCost: 30, damage: 50, description: '+50 dano estelar' },
      { name: 'Apocalipse Cósmico',    emoji: '🌌☄️', mpCost: 60, damage: 65, aoe: true, description: '65 dano em todos' },
      { name: 'SINGULARIDADE',         emoji: '🌑🌌', mpCost: 120, damage: 120, aoe: true, effect: 'ult', ultLevel: 1,
        ultName: 'SINGULARIDADE',
        ultLines: ['O Arcanista Supremo colapsa a realidade...', 'Um ponto infinito consome tudo...', 'SINGULARIDADE!'],
        ultColor: '#cc00ff', ultBg: 'radial-gradient(ellipse, #200040 0%, #000008 70%)',
        description: '🌌 ULT DIVINA: 120 dano em TODOS — a realidade colapsa.' },
    ],
  },
  rogue: {
    name: 'Espectro Eterno',
    emoji: '🌑💀',
    description: 'O Espectro torna-se pura escuridão. Invisível até para os deuses.',
    atkMultiplier: 2.8,
    defMultiplier: 1.6,
    hpBonusFlat: 30,
    ultLines: ['O Espectro dissolve-se nas trevas do Deus Corrompido...', 'Torna-se a própria morte...', 'ESPECTRO ETERNO!'],
    ultColor: '#00ffcc',
    ultBg: 'radial-gradient(ellipse, #001a15 0%, #000000 70%)',
    skillOverrides: [
      { name: 'Lâmina Negra',          emoji: '🌑🗡️', mpCost: 0,  damage: 20, description: '+20 dano sombrio' },
      { name: 'Veneno Eterno',         emoji: '☠️🌑', mpCost: 25, effect: 'poison', poisonDmg: 25, poisonTurns: 5, description: 'Veneno eterno: 25/t 5t' },
      { name: 'Névoa Perpétua',        emoji: '🌫️🌑', mpCost: 15, effect: 'dodge', description: 'Esquiva por 3 ataques' },
      { name: 'Decapitação Espectral', emoji: '💀⚡', mpCost: 45, damage: 70, effect: 'pierce', description: '70 dano, ignora TODA DEF' },
      { name: 'Eco Sombrio',           emoji: '👥🌑', mpCost: 30, damage: 35, description: 'Dois golpes de 35 dano' },
      { name: 'Dança da Extinção',     emoji: '🌑💃', mpCost: 55, damage: 55, aoe: true, effect: 'poison', poisonDmg: 20, poisonTurns: 4, description: '55 dano em todos + veneno letal' },
      { name: 'APAGAMENTO ETERNO',     emoji: '🌑⚡', mpCost: 120, damage: 150, effect: 'ult', ultLevel: 1,
        ultName: 'APAGAMENTO ETERNO',
        ultLines: ['O Espectro Eterno materializa-se atrás do alvo...', 'Mil lâminas de escuridão convergem...', 'APAGAMENTO ETERNO!'],
        ultColor: '#00ffcc', ultBg: 'radial-gradient(ellipse, #001a15 0%, #000000 70%)',
        description: '🌑 ULT DIVINA: 150 dano em 1 alvo + veneno letal.' },
    ],
  },
  necromancer: {
    name: 'Senhor da Extinção',
    emoji: '💀👑',
    description: 'O Ceifador torna-se a própria morte encarnada.',
    atkMultiplier: 2.4,
    defMultiplier: 1.8,
    hpBonusFlat: 50,
    ultLines: ['O Ceifador absorve as almas do Deus Corrompido...', 'Exércitos de deuses mortos respondem ao chamado...', 'SENHOR DA EXTINÇÃO!'],
    ultColor: '#aa00ff',
    ultBg: 'radial-gradient(ellipse, #200030 0%, #050005 70%)',
    skillOverrides: [
      { name: 'Pulso da Morte',        emoji: '💀⚡', mpCost: 0,  damage: 20, description: '+20 dano sombrio puro' },
      { name: 'Vampirismo Supremo',    emoji: '🩸💀', mpCost: 25, damage: 25, heal: 35, selfOnly: true, description: '+25 dano, drena 35HP' },
      { name: 'Praga Divina',          emoji: '🔮💀', mpCost: 20, effect: 'curse', curseDef: 15, curseAtk: 12, curseTurns: 6, description: '-15 DEF -12 ATK por 6 turnos' },
      { name: 'Exército Espectral',    emoji: '💀🌊', mpCost: 50, effect: 'necro_buff', necroAtkBonus: 20, necroBonusTurns: 6, description: '+20 dano para TODO o grupo por 6t' },
      { name: 'Detonação Sombria',     emoji: '🌑💥', mpCost: 35, damage: 30, aoe: true, description: '+30 dano em TODOS' },
      { name: 'Toque da Extinção',     emoji: '☠️👑', mpCost: 60, damage: 55, heal: 40, selfOnly: true, description: '+55 dano + drena 40HP' },
      { name: 'LEVANTE ETERNO',        emoji: '💀🌋', mpCost: 120, damage: 80, aoe: true, heal: 60, effect: 'ult', ultLevel: 1,
        ultName: 'LEVANTE ETERNO',
        ultLines: ['O Senhor da Extinção convoca todos os deuses caídos...', 'A morte absoluta caminha sobre a terra...', 'LEVANTE ETERNO!'],
        ultColor: '#aa00ff', ultBg: 'radial-gradient(ellipse, #250035 0%, #050005 70%)',
        description: '💀 ULT DIVINA: 80 dano em área + cura 60HP.' },
    ],
  },
  paladin: {
    name: 'Arauto Sagrado',
    emoji: '⚡🛡️',
    description: 'O Cruzado canaliza o poder dos deuses caídos. Luz e destruição em um só.',
    atkMultiplier: 2.0,
    defMultiplier: 2.2,
    hpBonusFlat: 100,
    ultLines: ['O Cruzado recebe a bênção do Deus Corrompido...', 'Luz divina corrompida emana de seu corpo...', 'ARAUTO SAGRADO!'],
    ultColor: '#ffdd00',
    ultBg: 'radial-gradient(ellipse, #2a2200 0%, #080600 70%)',
    skillOverrides: [
      { name: 'Veredicto Supremo',     emoji: '✨⚡', mpCost: 0,  damage: 16, description: '+16 dano sagrado divino' },
      { name: 'Cura Divina',           emoji: '💚✨', mpCost: 20, heal: 80, targetAlly: true, description: 'Cura 80HP em aliado' },
      { name: 'Égide Divina',          emoji: '🌟🛡️', mpCost: 25, effect: 'defense_up', defBonus: 25, defBonusTurns: 4, selfOnly: true, description: '+25 DEF por 4 turnos' },
      { name: 'Bênção Suprema',        emoji: '🙏🌟', mpCost: 60, heal: 90, effect: 'aoe_heal', description: 'Cura 90HP em TODOS' },
      { name: 'Martelo dos Deuses',    emoji: '🔨⚡', mpCost: 35, damage: 45, description: '+45 dano sagrado' },
      { name: 'Ressurreição Divina',   emoji: '✝️🌟', mpCost: 70, effect: 'revive', reviveHpPct: 0.8, targetAlly: true, description: 'Revive aliado com 80% HP' },
      { name: 'JULGAMENTO SUPREMO',    emoji: '⚡🌟', mpCost: 120, damage: 70, aoe: true, heal: 80, effect: 'ult', ultLevel: 1,
        ultName: 'JULGAMENTO SUPREMO',
        ultLines: ['O Arauto Sagrado abre os portais do céu...', 'Luz que aniquila e cura ao mesmo tempo...', 'JULGAMENTO SUPREMO!'],
        ultColor: '#ffdd00', ultBg: 'radial-gradient(ellipse, #302800 0%, #080600 70%)',
        description: '⚡ ULT DIVINA: 70 dano em TODOS + cura 80HP no grupo.' },
    ],
  },
  ranger: {
    name: 'Caçador Celestial',
    emoji: '🏹⭐',
    description: 'O Caçador transcende a física. Suas flechas rasgam a realidade.',
    atkMultiplier: 2.3,
    defMultiplier: 1.7,
    hpBonusFlat: 50,
    ultLines: ['O Caçador mira além do horizonte divino...', 'Flechas de energia pura materializam-se...', 'CAÇADOR CELESTIAL!'],
    ultColor: '#00aaff',
    ultBg: 'radial-gradient(ellipse, #001528 0%, #000508 70%)',
    skillOverrides: [
      { name: 'Flecha Celestial',      emoji: '🏹⭐', mpCost: 0,  damage: 18, description: '+18 dano celestial' },
      { name: 'Armadilha Letal',       emoji: '🪤⚡', mpCost: 20, effect: 'stun', stunTurns: 3, description: 'Atordoa o alvo por 3 turnos' },
      { name: 'Visão Divina',          emoji: '🦅🌟', mpCost: 25, effect: 'aim', aimBonus: 40, description: 'Próximo ataque +40 dano' },
      { name: 'Dilúvio Celestial',     emoji: '🌧️⭐', mpCost: 45, damage: 30, aoe: true, description: '+30 dano em TODOS' },
      { name: 'Flecha do Caos',        emoji: '💣🌌', mpCost: 35, damage: 50, description: '+50 dano explosivo' },
      { name: 'Disparo Divino',        emoji: '🎯⭐', mpCost: 40, damage: 40, effect: 'pierce', description: '40 dano, ignora toda DEF' },
      { name: 'CHUVA DO APOCALIPSE',   emoji: '🌧️☄️', mpCost: 120, damage: 85, aoe: true, effect: 'ult', ultLevel: 1,
        ultName: 'CHUVA DO APOCALIPSE',
        ultLines: ['O Caçador Celestial invoca as estrelas como flechas...', 'Mil projéteis divinos rasgam o céu...', 'CHUVA DO APOCALIPSE!'],
        ultColor: '#00aaff', ultBg: 'radial-gradient(ellipse, #001830 0%, #000508 70%)',
        description: '🏹 ULT DIVINA: 85 dano em TODOS + atordoa por 1 turno.' },
    ],
  },
  assassin: {
    name: 'Extinção Encarnada',
    emoji: '🌑⚔️',
    description: 'A Ombra torna-se a morte em forma física. Ninguém pode escapar.',
    atkMultiplier: 3.0,
    defMultiplier: 1.4,
    hpBonusFlat: 20,
    ultLines: ['A Ombra absorve as sombras do Deus Corrompido...', 'Torna-se indistinguível da própria morte...', 'EXTINÇÃO ENCARNADA!'],
    ultColor: '#334455',
    ultBg: 'radial-gradient(ellipse, #05080f 0%, #000001 70%)',
    skillOverrides: [
      { name: 'Corte da Eternidade',   emoji: '🌙💀', mpCost: 0,  damage: 25, description: '+25 dano mortal' },
      { name: 'Sentença Eterna',       emoji: '🎯💀', mpCost: 15, effect: 'mark', markMult: 2.5, markTurns: 4, description: '+150% dano por 4 turnos' },
      { name: 'Véu Eterno',            emoji: '🌫️💀', mpCost: 20, effect: 'dodge', description: 'Esquiva por 3 ataques' },
      { name: 'Guilhotina Suprema',    emoji: '💀⚡', mpCost: 45, damage: 90, effect: 'execute', description: '90 dano (5x se < 50% HP)' },
      { name: 'Quádruplo Fatal',       emoji: '⚡💀', mpCost: 35, damage: 28, description: 'Quatro golpes de 28 dano' },
      { name: 'Toxina da Eternidade',  emoji: '☠️🌑', mpCost: 40, damage: 25, effect: 'poison', poisonDmg: 30, poisonTurns: 6, description: '25 dano + veneno eterno (30/t 6t)' },
      { name: 'APAGAMENTO TOTAL',      emoji: '💀☄️', mpCost: 120, damage: 200, effect: 'ult', ultLevel: 1,
        ultName: 'APAGAMENTO TOTAL',
        ultLines: ['A Extinção Encarnada mira na essência do alvo...', 'Não há defesa, não há fuga, não há existência...', 'APAGAMENTO TOTAL!'],
        ultColor: '#446677', ultBg: 'radial-gradient(ellipse, #060a10 0%, #000001 70%)',
        description: '💀 ULT DIVINA: 200 dano em 1 alvo — ignora tudo.' },
    ],
  },
  elementalist: {
    name: 'Senhor dos Elementos',
    emoji: '🌀🌋',
    description: 'O Cataclista funde todos os elementos do universo em um só ser.',
    atkMultiplier: 2.4,
    defMultiplier: 1.6,
    hpBonusFlat: 40,
    ultLines: ['O Cataclista absorve todos os elementos divinos...', 'Fogo, gelo, raio e vácuo convergem...', 'SENHOR DOS ELEMENTOS!'],
    ultColor: '#ff6600',
    ultBg: 'radial-gradient(ellipse, #1a0f00 0%, #060200 70%)',
    skillOverrides: [
      { name: 'Labareda Primordial',   emoji: '🔥🌋', mpCost: 0,  damage: 22, description: '+22 dano primordial' },
      { name: 'Dardo do Apocalipse',   emoji: '❄️⚡', mpCost: 25, damage: 35, effect: 'slow', description: '+35 dano + lentidão eterna' },
      { name: 'Descarga Divina',       emoji: '⚡🌌', mpCost: 20, damage: 40, description: '+40 dano estelar divino' },
      { name: 'Colapso Primordial',    emoji: '🌊💥', mpCost: 55, damage: 50, aoe: true, description: '+50 dano elemental em TODOS' },
      { name: 'Tempestade Divina',     emoji: '🌨️⚡', mpCost: 35, damage: 30, aoe: true, effect: 'slow', description: '+30 em TODOS + lentidão' },
      { name: 'Extinção Elemental',    emoji: '🌋💀', mpCost: 65, damage: 75, aoe: true, description: '75 dano em todos' },
      { name: 'OMEGA PRIMORDIAL',      emoji: '🌀☄️', mpCost: 120, damage: 110, aoe: true, effect: 'ult', ultLevel: 1,
        ultName: 'OMEGA PRIMORDIAL',
        ultLines: ['O Senhor dos Elementos libera todos os poderes...', 'O universo inteiro colapsa num único ponto...', 'OMEGA PRIMORDIAL!'],
        ultColor: '#ff6600', ultBg: 'radial-gradient(ellipse, #220f00 0%, #060200 70%)',
        description: '🌀 ULT DIVINA: 110 dano em TODOS + lentidão.' },
    ],
  },
  berserker: {
    name: 'Flagelante Primordial',
    emoji: '🪓🔥',
    description: 'O Flagelante abandona toda humanidade. Torna-se força pura e destruição.',
    atkMultiplier: 3.2,
    defMultiplier: 1.3,
    hpBonusFlat: 120,
    ultLines: ['O Flagelante absorve a raiva do Deus Corrompido...', 'Toda sanidade desaparece, só resta destruição...', 'FLAGELANTE PRIMORDIAL!'],
    ultColor: '#ff2200',
    ultBg: 'radial-gradient(ellipse, #300000 0%, #0a0000 70%)',
    skillOverrides: [
      { name: 'Machadada Primordial',  emoji: '🪓🌋', mpCost: 0,  damage: 28, description: '+28 dano brutal primordial' },
      { name: 'Êxtase Divino',         emoji: '😡🔥', mpCost: 20, effect: 'berserk', berserkAtkBonus: 22, berserkDefPenalty: 5, berserkTurns: 4, description: '+22 ATK -5 DEF por 4 turnos' },
      { name: 'Rugido do Abismo',      emoji: '🦁🌋', mpCost: 15, effect: 'taunt', description: 'Todos atacam você por 3 turnos' },
      { name: 'Devastação Total',      emoji: '💥🔥', mpCost: 40, damage: 55, effect: 'ignore_half_def', description: '55 dano, ignora toda DEF' },
      { name: 'Frenesi Quíntuplo',     emoji: '⚡🪓', mpCost: 30, damage: 22, description: 'Cinco golpes de 22 dano' },
      { name: 'Êxtase Primordial',     emoji: '🩸🌋', mpCost: 50, damage: 45, effect: 'rage_scale', description: '45 dano (escala até 6x com HP baixo)' },
      { name: 'RAGNAROK',              emoji: '🪓🌋', mpCost: 120, damage: 130, aoe: true, effect: 'ult', ultLevel: 1,
        ultName: 'RAGNAROK',
        ultLines: ['O Flagelante Primordial abandona a existência...', 'Destruição total e absoluta se manifesta...', 'RAGNAROK!'],
        ultColor: '#ff2200', ultBg: 'radial-gradient(ellipse, #380000 0%, #0a0000 70%)',
        description: '🪓 ULT DIVINA: 130 dano em TODOS, escala com HP perdido.' },
    ],
  },
  guardian: {
    name: 'Bastião Eterno',
    emoji: '🗿⚡',
    description: 'O Bastião torna-se uma montanha viva. Imortal e inquebrável.',
    atkMultiplier: 1.8,
    defMultiplier: 3.0,
    hpBonusFlat: 200,
    ultLines: ['O Bastião absorve a resistência do Deus Corrompido...', 'Seu corpo torna-se pedra divina...', 'BASTIÃO ETERNO!'],
    ultColor: '#aabbcc',
    ultBg: 'radial-gradient(ellipse, #101515 0%, #030405 70%)',
    skillOverrides: [
      { name: 'Esmagamento Divino',    emoji: '🗿⚡', mpCost: 0,  damage: 14, description: '+14 dano divino' },
      { name: 'Desafio Total',         emoji: '📢🗿', mpCost: 10, effect: 'taunt', description: 'TODOS atacam o Bastião por 3 turnos' },
      { name: 'Muralha Divina',        emoji: '🏰⚡', mpCost: 30, effect: 'wall', wallTurns: 4, description: 'Grupo recebe 10% do dano por 4t' },
      { name: 'Represália Divina',     emoji: '🔄⚡', mpCost: 25, effect: 'counter', counterPct: 1.0, description: 'Reflete 100% do próximo dano' },
      { name: 'Couraça Suprema',       emoji: '⛩️🗿', mpCost: 20, effect: 'defense_up', defBonus: 45, defBonusTurns: 4, selfOnly: true, description: '+45 DEF por 4 turnos' },
      { name: 'Pancada Sagrada',       emoji: '🛡️💥', mpCost: 40, damage: 40, effect: 'stun', stunTurns: 2, description: '+40 dano e atordoa por 2 turnos' },
      { name: 'FORTALEZA DO DEUS',     emoji: '🗿🌋', mpCost: 120, effect: 'ult', ultLevel: 1,
        ultName: 'FORTALEZA DO DEUS',
        ultLines: ['O Bastião Eterno torna-se a própria rocha do universo...', 'Nenhuma força pode derrubar esta montanha...', 'FORTALEZA DO DEUS!'],
        ultColor: '#aabbcc', ultBg: 'radial-gradient(ellipse, #121818 0%, #030405 70%)',
        damage: 50, aoe: true,
        description: '🗿 ULT DIVINA: Grupo invulnerável por 4 turnos + 50 dano em área.' },
    ],
  },
  druid: {
    name: 'Espírito de Gaia',
    emoji: '🌿✨',
    description: 'O Vidente funde-se com a natureza primordial. A vida emana de seu corpo.',
    atkMultiplier: 1.8,
    defMultiplier: 2.0,
    hpBonusFlat: 80,
    ultLines: ['O Vidente une-se à alma do Deus Corrompido...', 'A natureza primordial desperta...', 'ESPÍRITO DE GAIA!'],
    ultColor: '#00ff88',
    ultBg: 'radial-gradient(ellipse, #001a08 0%, #000300 70%)',
    skillOverrides: [
      { name: 'Espinhos Divinos',      emoji: '🌿⚡', mpCost: 0,  damage: 14, description: '+14 dano divino' },
      { name: 'Cura de Gaia',          emoji: '🍃✨', mpCost: 15, heal: 90, targetAlly: true, description: 'Cura 90HP em aliado' },
      { name: 'Seiva Primordial',      emoji: '♻️🌿', mpCost: 20, effect: 'regen', regenHp: 35, regenTurns: 6, targetAlly: true, description: '+35HP/turno por 6 turnos' },
      { name: 'Floresta Sagrada',      emoji: '🌸✨', mpCost: 55, heal: 110, effect: 'aoe_heal', description: 'Cura 110HP em TODOS' },
      { name: 'Raízes Eternas',        emoji: '🌱⚡', mpCost: 25, effect: 'stun', stunTurns: 3, description: 'Enraíza por 3 turnos' },
      { name: 'Furacão Primordial',    emoji: '🍂💥', mpCost: 45, damage: 28, aoe: true, effect: 'poison', poisonDmg: 18, poisonTurns: 4, description: '+28 em área + veneno divino' },
      { name: 'GAIA DESPERTA',         emoji: '🌍✨', mpCost: 120, heal: 150, effect: 'ult', ultLevel: 1,
        ultName: 'GAIA DESPERTA',
        ultLines: ['O Espírito de Gaia chama a mãe terra...', 'A vida flui sem limites por todos...', 'GAIA DESPERTA!'],
        ultColor: '#00ff88', ultBg: 'radial-gradient(ellipse, #001f08 0%, #000300 70%)',
        description: '🌍 ULT DIVINA: Cura 150HP em TODOS + ressuscita aliados.' },
    ],
  },
  bard: {
    name: 'Trovador do Apocalipse',
    emoji: '🎵💀',
    description: 'O Trovador compõe a música do fim dos tempos. Cada nota é uma catástrofe.',
    atkMultiplier: 2.1,
    defMultiplier: 1.9,
    hpBonusFlat: 60,
    ultLines: ['O Trovador ouve a melodia do Deus Corrompido...', 'Uma música que pode destruir mundos...', 'TROVADOR DO APOCALIPSE!'],
    ultColor: '#ff8800',
    ultBg: 'radial-gradient(ellipse, #1a0800 0%, #060200 70%)',
    skillOverrides: [
      { name: 'Nota da Extinção',      emoji: '🎵💀', mpCost: 0,  damage: 16, description: '+16 dano sonoro divino' },
      { name: 'Cântico Sagrado',       emoji: '🎶✨', mpCost: 15, heal: 65, targetAlly: true, description: 'Cura 65HP em aliado' },
      { name: 'Hino do Caos',          emoji: '🎸💥', mpCost: 20, effect: 'group_atk_up', atkGroupBonus: 14, atkGroupTurns: 4, description: '+14 ATK para TODOS por 4t' },
      { name: 'Épico do Apocalipse',   emoji: '🎺💀', mpCost: 60, effect: 'balada', baladaAtk: 18, baladaDef: 18, baladaHeal: 70, description: '+18 ATK +18 DEF +70HP para TODOS' },
      { name: 'Dissonância Divina',    emoji: '📯💀', mpCost: 25, damage: 28, aoe: true, effect: 'stun', stunTurns: 2, description: '+28 em todos + atordoa' },
      { name: 'Réquiem Eterno',        emoji: '🎻💀', mpCost: 50, damage: 55, description: '+55 dano letal divino' },
      { name: 'SINFONIA DO OBLÍVIO',   emoji: '🎼☄️', mpCost: 120, damage: 90, aoe: true, effect: 'ult', ultLevel: 1,
        ultName: 'SINFONIA DO OBLÍVIO',
        ultLines: ['O Trovador entoa a última canção do universo...', 'O cosmos para para ouvir seu fim...', 'SINFONIA DO OBLÍVIO!'],
        ultColor: '#ff8800', ultBg: 'radial-gradient(ellipse, #1e0900 0%, #060200 70%)',
        description: '🎼 ULT DIVINA: 90 dano em TODOS + máximo de buffs para o grupo.' },
    ],
  },
};

export const TRANSFORM_ITEM = {
  id: 'ancient_god_essence',
  name: 'Essência do Deus Corrompido',
  emoji: '🌟',
  price: 0,
  attackBonus: 0,
  defenseBonus: 0,
  description: 'Dropa do Deus Corrompido. Permite transformação por 6 turnos (uso único por combate).',
  consumable: false,
  permanent: true,
  isTransformItem: true,
};